#
# Run repoman via travis
# Based on https://github.com/mrueg/repoman-travis
#
language: python
python:
    - pypy
before_install:
    - sudo apt-get -qq update
    - pip install lxml
before_script:
    - mkdir travis-overlay
    - shopt -s extglob
    - export PORTAGE_VER="2.3.5"
    - mv !(travis-overlay) travis-overlay/
    - mv .git .travis_repoman-copyright.patch travis-overlay/
    - wget "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" -O portage-${PORTAGE_VER}.tar.gz
    - wget "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" -O portage-tree.tar.gz
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage /usr/portage/distfiles
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - tar xzf portage-${PORTAGE_VER}.tar.gz && mv portage-portage-${PORTAGE_VER} portage-${PORTAGE_VER}
    - tar xzf portage-tree.tar.gz -C /usr/portage --strip-components=1
    - cp portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/
    - ln -s /usr/portage/profiles/default/linux/amd64/13.0 /etc/portage/make.profile
    - mv portage-${PORTAGE_VER} travis-overlay /tmp
    - cd /tmp/portage-${PORTAGE_VER}/repoman
    - patch -p1 < /tmp/travis-overlay/.travis_repoman-copyright.patch
    - cd /tmp/travis-overlay
script:
    - python ../portage-${PORTAGE_VER}/repoman/bin/repoman full -d
# You can append own scripts after this line
